name: Historization (slim)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["scraper"]
    types:
      - completed

jobs:
  add_latest_results_if_changed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout demodiff/daten
      uses: actions/checkout@v3
      with:
        repository: demodiff/daten
        token: ${{ secrets.PAT }}
        path: data_raw
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Historize latest results.json
      run: |
        git show HEAD:data/results.json > data_raw/berlin/$(git show -s --format=%cd --date=format:'%Y%m%d_%H%M%S')_$(git rev-parse HEAD).json

    - name: Remove duplicates
      run: | 
        sudo snap install fclones
        fclones group data_raw/ > dupes.txt
        cat dupes.txt
        fclones remove < dupes.txt
    
    - name: Create summary
      run: |
        python scripts/create_summary.py
    
    - name: Commit files
      run: |
        cd data_raw
        git config --local user.email "actions@users.noreply.github.com"
        git config --local user.name "demodiffbot"
        git add --all
        git diff-index --quiet HEAD || git commit -a -m "Berlin: Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: demodiff/daten
        directory: data_raw
        github_token: ${{ secrets.PAT }}
