name: parser

on:
  workflow_run:
    workflows: ["scraper"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v3
      with:
        path: "requirements.txt"

    - name: Parse demo announcements
      run: |
        python3 scripts/json2jsonl.py > data/results.jsonl
        python3 scripts/jsonl2stats.py
        
    - name: Temporarily fix permission error in git # https://github.com/actions/checkout/issues/760#issuecomment-1097501613
      run: git config --global --add safe.directory /__w/demodiff/berlin

    - name: Commit and push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'Automatisierte Aktualisierung der Versammlungen'
        rebase: true
        name: 'parser'
        files: data/
