name: releaser

on:
  schedule:
    - cron : '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set date as env
      run: |
        echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      id: version

    - name: Create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.version.outputs.builddate }}
        overwrite: false
        release_name: ${{ steps.version.outputs.builddate }} 
