name: releaser

on: push
#  schedule:
#    - cron : '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: data/jsonl/
        overwrite: false
        file_glob: true
        release_name: demodiff-berlin-${{ steps.date.outputs.date }}
