name: scraper

on:
  schedule:
    - cron : '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download demo announcements
      run: |
        rm data/results.json
        pushd data
        wget -O results.json https://www.berlin.de/polizei/service/versammlungsbehoerde/versammlungen-aufzuege/index.php/index/all.json
        popd
    - name: Temporarily fix permission error in git # https://github.com/actions/checkout/issues/760#issuecomment-1097501613
        run: git config --global --add safe.directory /__w/demodiff/berlin
    - name: Commit and push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'scraper: add demo announcements'
        rebase: true
        name: 'scraper'
        files: data/
