name: sender

on:
  workflow_run:
    workflows: ["parser"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tweet
        uses: mugi111/tweet-trigger-release@v1.1
        with:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          access_token_key: ${{ secrets.ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
          tweet_body: 'Die #Polizei #Berlin aktualisierte die Demoliste. #demodiff https://github.com/demodiff/berlin/commit/${{ env.GITHUB_SHA }}'
