name: sender

on:
  workflow_run:
    workflows: ["parser"]
    types:
      - completed

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: Eomm/why-don-t-you-tweet@v1
        with:
          tweet-message: "Die Polizei Berlin aktualisierte ihre Versammlungsliste. #demodiff https://github.com/demodiff/berlin/commit/${{ env.GITHUB_SHA }}"
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
