name: sender

on:
  workflow_run:
    workflows: ["parser"]
    types:
      - completed

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Die Polizei Berlin aktualisierte ihre Versammlungsliste. https://github.com/demodiff/berlin/commit/${{ GITHUB_SHA }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
