name: writer

on:
  workflow_run:
    workflows: ["parser"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Write demo announcements
      run: |
        git show HEAD:data/results.jsonl > data/jsonl/$(git show -s --format=%cd --date=format:'%Y%m%d-%H%M%S')-$(git rev-parse HEAD).jsonl
        
    - name: Commit and push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        commit-message: 'Automatisierte Aktualisierung der Versammlungen'
        rebase: true
        name: 'writer'
        files: data/jsonl/
